apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}-querybackend
spec:
  replicas: {{ .Values.querybackend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-querybackend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-querybackend
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.querybackend.image.repository }}:{{ .Values.querybackend.image.tag}}"
          ports:
            - name: http
              containerPort: {{ .Values.querybackend.service.ports.port }}
              protocol: TCP
