apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{.Release.Name}}-route
spec:
  selector:
    app: {{ .Release.Name }}-backend
  to:
    kind: Service
    name: {{.Release.Name}}-service
  port: 
    targetPort: {{.Values.backend.service.ports.targetPort}}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect     
