apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.ports.port }}
      targetPort: {{.Values.backend.service.ports.targetPort}}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-backend
